### ISSUE TITLE
Provider Distributed Cloud connection error

### ISSUE THREAD

**Issue by BarryHaines** [f5devcentral/ps-convert#1]
Environment

F5 Internal Staging

Summary
When trying to test the connection to an XC tenant from the Policy Supervisor I get connection testing failed after connected to agent and Retrieved Secret Info.  From the View details for the provider it fails with error fetching endpoints.  If I use curl to call the API endpoint for namespaces, with the same API token it works fine and I can use the XC console without an issue.  

I believe the issue is a permissions issue in the XC tenant but I need to identify what permissions are required for the policy supervisor XC provider.

**Comment by nikg** [comment]
Have you tried curl to XC from the machine on which you run the agent?

**Comment by BarryHaines** [comment]
Curl works with the same api token.

Regards
Barry

**Comment by dpruettf5** [comment]
Hi Barry - 

Currently, ves-io-admin-role is required for 'All Application Namespaces' and 'System' namespace options. Thanks for bringing this up, the docs do not specify and we will update.
