### ISSUE TITLE
Conversion failed with no error message

### ISSUE THREAD

**Issue by botros23** [f5devcentral/ps-convert#11]
Conversion failed with no error message other than "Failed Conversion"
"conversionSummary": {
		"createdOn": "2023-08-11T14:19:04.747159867Z",
		"source": "AWAF",
		"target": "ONEWAF",
		"fullConvert": 13831,
		"partialConvert": 0,
		"noneConvert": 50272,
		"warningConvert": 0,
		"errorConvert": 0
	},

**Comment by nikg** [comment]
@botros23 Thanks for flagging, we confirmed this is an issue -- investigating

**Comment by nikg** [comment]
@botros23 is this still an issue with the policy you were testing? Many AWAF -> ONEWAF conversions have been fixed, if it's not working for you still please email me a zipped policy.
