### ISSUE TITLE
The PS converter/supervisor allow service policy rule does not match because of missing HTTP headers and all traffic is blocked !

### ISSUE THREAD

**Issue by Nikoolayy1** [f5devcentral/ps-convert#13]
When I migrated a test WAF BIG-IP policy I saw that all traffic is blocked as my traffic matches the default deny in the Service policy. 

To fix this I had to remove the HTTP headers in the Allow Rule for it to match and add an allow URL as issue https://github.com/f5devcentral/ps-convert/issues/2 is still not resolved.

Also if I remove all the headers and leave the wildcard header with a name * , I am still blocked.

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/46426464-f2c2-4ccd-a4fe-f35b3c6f4ce0)

**Comment by nikg** [comment]
Hi @Nikoolayy1  - we need to work through this one in the Converter logic, thanks for flagging. We'll update ASAP.

**Comment by nikg** [comment]
Default Deny behaviour is now replaced with Default "Allow All" at the end of service policy chain with "Next Policy" setting.
