### ISSUE TITLE
Policy deployment fail with error 500 message

### ISSUE THREAD

**Issue by j-salinas-f5** [f5devcentral/ps-convert#14]
Error detail:
{
    "name": "ApiError",
    "url": "https://policysupervisor.io/api/v1/commands/deploy-convert",
    "status": 500,
    "statusText": "",
    "body": {
        "code": 2,
        "message": "methods, get policy by type BASE_APP_SEC_POLICY: failed to get file content as string: failed to get file content: GET https://gitlab.policysupervisor.io/api/v4/projects/436949/repository/files/policy.json: 404 {message: 404 Commit Not Found}",
        "details": []
    },
    "request": {
        "method": "POST",
        "url": "/api/v1/commands/deploy-convert",
        "body": {
            "policyId": "59ae1054-e755-493a-809f-0673f961c205",
            "targets": [
                "XC"
            ],
            "notes": "test"
        },
        "errors": {
            "400": "Invalid argument",
            "401": "Returned when the user does not have permission to access the resource.",
            "404": "Resource was not found.",
            "500": "Internal server error"
        }
    }
}

**Comment by nikg** [comment]
HI @j-salinas-f5 - we're investigating, but in the meantime can you please try again, there was an issue with the backend accessibility.

**Comment by nikg** [comment]
should be resolved.
