### ISSUE TITLE
Policy Supervisor injects code fragment into HTTP PATH Service Policy configuration

### ISSUE THREAD

**Issue by yogibear15** [f5devcentral/ps-convert#15]
This appears to occur on every ASM policy we attempt to migrate from SL -> XC.  It might be something in the SL standard policy that triggers it, I've not yet tried with a non-SL one.

After performing conversion and deployment to XC of an ASM/AWAF policy, Service Policy rules under HTTP Path are populated:

![image](https://github.com/f5devcentral/ps-convert/assets/16494017/4b4728e1-e944-483d-b746-bac33a029b4d)

Below that is found:

![image](https://github.com/f5devcentral/ps-convert/assets/16494017/aba6a89c-56a0-415d-9880-a8f3befca4c7)

That shouldn't be.

**Comment by nikg** [comment]
Fixed with multiple other updates
