### ISSUE TITLE
F5 BIG-IP disabled signatures under content profiles/URLS are not transferred to F5 XC by the supervisor 

### ISSUE THREAD

**Issue by Nikoolayy1** [f5devcentral/ps-convert#17]
Maybe as XC cloud as of now does not support content profiles the disabled signatures under content profiles can't be transferred to XC cloud service policy. Maybe if the XC supervisor could make a higher priority  rules that have Content-Type header as match  that disable or enable the Content Specific signatures.

**Comment by yogibear15** [comment]
What Nikolay is reporting here is that if ASM policy has signature overrides on a XML/JSON Content Profile, there is no resultant config migrated to XC.
We need to figure out what the correct behavior should be given that XC does not use Content profiles and handles structured POST data in a different fashion

**Comment by Nikoolayy1** [comment]
Another way is the service policy to have rules for url and content-type signatures to be disabled and then then under the load balancer waf exclusion rule to have the signatures for parameters / cookies / http headers as for them Context value can be specified that is the name of the object and for URL or content profile signatures this context option is not available.
