### ISSUE TITLE
PS doesn't add response codes properly to XC app firewall

### ISSUE THREAD

**Issue by j-salinas-f5** [f5devcentral/ps-convert#18]
If the SL policy have any custom http response codes configured, the custom codes are migrated correctly to XC app firewall but the default ones (100-399) are not included, which ends up blocking all valid traffic.
By default ASM accepts all response codes from 100 to 399 as valid responses. 
https://techdocs.f5.com/kb/en-us/products/big-ip_asm/manuals/product/asm-implementations-13-0-0/31.html

**Comment by nikg** [comment]
Fixed with the update. By default adding "200-208" and "300-308" as per discussion with team.
