### ISSUE TITLE
F5  supervisor convert the disallowed url from BIG-IP to XC service policy allow list

### ISSUE THREAD

**Issue by Nikoolayy1** [f5devcentral/ps-convert#2]
When converting an BIG-IP WAF policy that has allowed url list and disallowed url list I saw that the converted XC service policy adds the disallowed url to the XC service policy's allowed rule and the allowed url are missing. The example below "/test" url was in disallowed list on the BIG-IP.

<img width="763" alt="f5xc-issue" src="https://github.com/f5devcentral/ps-convert/assets/23706402/3a8fe20a-612c-4ab4-b5dc-d99220161def">

<img width="579" alt="f5xc-issue1" src="https://github.com/f5devcentral/ps-convert/assets/23706402/77af1988-6d0c-4ec8-bfc9-ca01f2d77823">

**Comment by nikg** [comment]
"Disallow URL" will be supported shortly (end of Nov 2023), this requires changes to CDP schema and will be completed soon.
The recent updates result in signatures exceptions URLs (with context: ANY) going into Service Policy in XC.

**Comment by nikg** [comment]
Disallow URL behavior planned update shortly.
