### ISSUE TITLE
F5 PS converter does not enable Automatic Attack Signatures Tuning and Attack Signatures Staging

### ISSUE THREAD

**Issue by Nikoolayy1** [f5devcentral/ps-convert#24]
Maybe having the option during a migration from BIG-IP to XC be able to select if to enable or disable this options.

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/3527c39e-c931-4eed-ba70-7e4a04a63cb4)

**Comment by nikg** [comment]
On the roadmap of the next set of issues to address.

**Comment by nikg** [comment]
Fixed in the latest release.
