### ISSUE TITLE
The PS converter wrongly converts the URL disabled signatures 

### ISSUE THREAD

**Issue by Nikoolayy1** [f5devcentral/ps-convert#27]
For example the below signatures are dissabled for URL /niki and the wildcard url

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/4799f53e-50f0-4004-8dd0-4ab02ea200b0)

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/644c26d6-07b2-4ee2-97b4-6f45f020c5c3)

The policy converter converts to the below config. The issue is that the Context name in XC can be used only for signatures for parameters, cookies and headers not url level or Request body level context, so the signature 200093 will still block the request and 200000099 needs to be disabled for not Context Any but URL context as for each url that has disabled signatures a security policy rule is needed that matches the url with the path regex or suffix path option. See https://github.com/f5devcentral/ps-convert/issues/17 

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/eb3ace02-7aa6-49ef-924d-45b9675bf932)

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/4c3e78c4-21aa-4f61-8c50-d286b10041c1)

Rule 1 path

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/68ca8c91-86a0-4076-ba69-be494f59dad5)

Rule 2 path

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/01c82294-75d3-4bf8-80c2-d0af98cffe08)

**Comment by nikg** [comment]
Should be fixed in the latest updates.
