### ISSUE TITLE
Max headers and Max parameters should not be converted to Dist Cloud

### ISSUE THREAD

**Issue by yogibear15** [f5devcentral/ps-convert#28]
The HTTP Protocol Compliance sub-violation settings in ASM policy for "Check maximum number of headers" and "Check maximum number of parameters", represented in XML as:

```
<http_protocol_compliance_setting maximum_headers="25" policy_builder_tracking="enabled" name="Check maximum number of headers">enabled</http_protocol_compliance_setting>
<http_protocol_compliance_setting maximum_parameters="500" policy_builder_tracking="enabled" name="Check maximum number of parameters">enabled</http_protocol_compliance_setting>
```

The associated sub-violations for those are not supported on XC.  As such this configuration does not need to be migrated.

The current behavior seems that the config is converted to Requests Constraints:

![image](https://github.com/f5devcentral/ps-convert/assets/16494017/ec30c3ae-bfa4-4168-83a9-4852fc6338b2)

We saw some inconsistencies here, in that on the first attempt there was Request Constraints config deployed and on the second attempt there was not... but in any case, there is no need to migrate this config.

Thanks

**Comment by nikg** [comment]
Will check, this mapping into XC should be disabled as not supported.
