### ISSUE TITLE
Signature Staging setting is not converted

### ISSUE THREAD

**Issue by yogibear15** [f5devcentral/ps-convert#29]
For reference, the converted CDP format policy can be found:
silverline-template-addedsigs
160dd8a6-14f2-4b8a-9623-c55c541751ca

This is converted from the template policy we were working with on Wednesday.  I can't attach XML document here, but the relevant config in XML is:

```
  <attack_signatures>
...
    <enable_staging>true</enable_staging>
```

There doesn't appear to be an equivalent setting in the CDP format policy.
When deployed to XC, the setting changes to Disabled, which is incorrect:

![image](https://github.com/f5devcentral/ps-convert/assets/16494017/e2802934-26c9-4ac4-aded-e3743525602a)

**Comment by nikg** [comment]
will need to be implemented.

**Comment by nikg** [comment]
fixed in the latest release.
