### ISSUE TITLE
F5 XC supervisor does not convert disallowed and allowed file types from BIG-IP

### ISSUE THREAD

**Issue by Nikoolayy1** [f5devcentral/ps-convert#3]
The supervisor does not convert the allowed and disallowed file types to the XC service policy but this is supported as shown in https://clouddocs.f5.com/training/community/volterra-workshop/html/class2/module1/lab2/lab2.html

**Comment by dpruettf5** [comment]
Thanks for bringing this up, I am able to reproduce the behavior and will file a bug.

**Comment by nikg** [comment]
File Types are now going into the correct locations in XC (Service Policy).
