### ISSUE TITLE
Enable redeployment for a converted policy

### ISSUE THREAD

**Issue by yogibear15** [f5devcentral/ps-convert#31]
When Deploying a policy, it first performs a conversion of the CDP policy to XC-compatible format.  This can be time consuming, often up to 10 minutes.  Once this completes, the operator should continue to deployment.

If the operator is interrupted (say, has to login again after some time), or if the deployment fails for any reason, it does not seem possible to re-attempt the deploy with the already-converted policy.

The 'Conversion' appears to be available, but a Conversion cannot be deployed:
![image](https://github.com/f5devcentral/ps-convert/assets/16494017/e2178a1b-20e4-4a2f-8348-23a04938ea77)

In this instance the operator must start the process again, and wait for the conversion to complete.  It would be better if the XC-converted policy object be stored and redeployment attempts made possible, without having to re-convert.

**Comment by nikg** [comment]
Current workflow cannot support re-deployment of "in-flight" conversion objects. Will need to get additional feedback on priority of this as a feature. Pls email me.
