### ISSUE TITLE
Service policy name  too long error when deploying policy

### ISSUE THREAD

**Issue by j-salinas-f5** [f5devcentral/ps-convert#33]
`Error: could not create service policy (status: 400){"code":3,"details":[{"type_url":"type.googleapis.com/ves.io.stdlib.server.error.Error","value":"�CreateResource: Failed transaction handling service_policy: STM Error, PreDBUndo Error: %!s(\\u003cnil\\u003e): Applying transaction function: Validating private create request: Validating private API Create: Name ves-io-service-policy-POLICYNAME-policy-signaturesapplied-POLICYNAME-policy-signaturesprotections(127) too long only 126 allowed;2023-09-16 14:03:01.203745042 +0000 UTC m=+199364.304858539"}],"message":"For service_policy default/POLICYNAME-policy-signaturesapplied configuration for child object service_policy_rule ves-io-service-policy-POLICYNAME-policy-signaturesapplied-POLICYNAME-policy-signaturesprotections is wrong - Name ves-io-service-policy-POLICYNAME-policy-signaturesapplied-POLICYNAME-policy-signaturesprotections(127) too long only 126 allowed"}`
i can provide more details internally.

**Comment by nikg** [comment]
Fixed in the latest updates.
