### ISSUE TITLE
The new version of the XC supervisor creates query parameter XC service policy rules for some reason

### ISSUE THREAD

**Issue by Nikoolayy1** [f5devcentral/ps-convert#34]
For some reason the global 'test' parameter is in a deny rule and the url specific parameter "urlparam" is in another rule in the service policy. The query option is only for parameters and that are in the URL not in the POST body , so I do not see the logic as signatures can be stopped for parameter contexts  and for url specific parameters the url match is needed not query parameter match.

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/edd0c11f-f557-4b10-969f-031b5785ed6e)

How it should look like:

![image](https://github.com/f5devcentral/ps-convert/assets/23706402/854d6fb4-4f1c-4a9c-844b-bdc55916392e)

**Comment by nikg** [comment]
Fixed in the latest updates.
