### ISSUE TITLE
AWAF v16.1 XML policy import fails.

### ISSUE THREAD

**Issue by steveh565** [f5devcentral/ps-convert#6]
Tried to import an AWAF policy I created on v16.1 in my lab, and it fails with output: 
Command status: JOB_FAILED

When I try to Export the Report for the policy conversion job, I get the following output:
{
    "name": "ApiError",
    "url": "https://policysupervisor.io/api/v1/commands/convert/44bf666c-6ce4-49ac-9b0d-e491bc16ef6b/reportZip",
    "status": 500,
    "statusText": "Internal Server Error",
    "body": {
        "code": 2,
        "message": "conversion command is failed",
        "details": []
    },
    "request": {
        "method": "GET",
        "url": "/api/v1/commands/convert/{id}/reportZip",
        "path": {
            "id": "44bf666c-6ce4-49ac-9b0d-e491bc16ef6b"
        },
        "errors": {
            "400": "Invalid argument",
            "401": "Returned when the user does not have permission to access the resource.",
            "404": "Resource was not found.",
            "500": "Internal server error"
        }
    }
}

**Comment by BarryHaines** [comment]
This is a duplicate issue with issue number 4

**Comment by nikg** [comment]
Confirmed issue, we're on it and should be updated shortly. thanks!

**Comment by nikg** [comment]
Issue resolved and fixed.
