### ISSUE TITLE
RFE - Override for Service policy error maximum items of 1024 

### ISSUE THREAD

**Issue by BarryHaines** [f5devcentral/ps-convert#7]
Current Behaviour: 
Service policy fail to deploy with the message "Error: could not create service policy" and "Field spec.rule_choice.rule_list.rules.spec.waf_action.action_type.app_firewall_detection_control.exclude_signature_contexts should have maximum items of 1024, got 1580 in request.".  This requires the review of the individual policy to remove any non-contextual (Global disabled) signatures.

Request Behaviour:
Provide an override to allow in the deployment to allow the creation of the service policy without the global disabled signatures and leave only the signature that are disabled on specific context e.g. URL or parameter.

**Comment by nikg** [comment]
Confirmed, it's an issue with how the service policies are created and we'll need to do some additional dev to batch multiple for items above 1024. We'll update as soon as this feature is added.

**Comment by yogibear15** [comment]
@nikg we don't need to support >1024 individual signature overrides.  If there are that many, they will be a category of signatures (most likely Low Accuracy) that can be corrected in either the source file, or on the destination XC configuration.

I see that the error is a warning only:
`		{
			"Name": "",
			"Status": "WARNING",
			"Destination": "[0].spec.rule_list.rules.[0].spec.waf_action.app_firewall_detection_control.exclude_signature_contexts",
			"Description": "Array must have at most 1024 items",
			"ValueSource": null,
			"ValueDestination": null,
			"Converted": false,
			"ConvertedFromPreconverted": false,
			"Error": false,
			"Warning": true
		},
		{
			"Name": "",
			"Status": "WARNING",
			"Destination": "[0].spec.rule_list.rules.[1].spec.waf_action.app_firewall_detection_control.exclude_signature_contexts",
			"Description": "Array must have at most 1024 items",
			"ValueSource": null,
			"ValueDestination": null,
			"Converted": false,
			"ConvertedFromPreconverted": false,
			"Error": false,
			"Warning": true
		},`

Can we just have an option to override the warning and continue deployment?

**Comment by nikg** [comment]
If there are more than 50 signature overrides, XC Firewall is set to mode High and Medium Accuracy. Signature overrides are not added in this case.
